Repository nscharrenberg/Multi-agent-Surveillance, pull requests merged in 2022-02, with the labels that each got.

#4 add read me
  README.md
Labels: documentation

#7 5 setup base structure
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/.gitkeep
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/BaseController.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/.gitkeep
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/.gitkeep
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Angle.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Area.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Collision.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Door.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Guard.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Intruder.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Item.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Player.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/ShadowTile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Teleporter.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Tile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Wall.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Window.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/.gitkeep
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/GameRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/MapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/PlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/.gitkeep
  src/main/java/module-info.java
  src/main/resources/com/nscharrenberg/um/multiagentsurveillance/hello-view.fxml
Labels: enhancement

#16 13 import map
  project/.idea/workspace.xml
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IMapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/exceptions/BoardNotBuildException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/exceptions/InvalidTileException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/exceptions/ItemAlreadyOnTileException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/exceptions/ItemNotOnTileException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Angle.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Area.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/ShadowTile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Teleporter.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Tile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/TileArea.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/MapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/AngleConverter.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/files/FileItems.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/files/MapImporter.java
  src/test/java/headless/MapBuildTest.java
  src/test/java/headless/MapImporterTest.java
  src/test/resources/maps/testmap.txt
Labels: enhancement

#22 17 movement collision
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IMapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IPlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/exceptions/CollisionException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Angle.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Tile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/MapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/PlayerRepository.java
  src/test/java/headless/MapBuildTest.java
Labels: enhancement

#25 14 character vision
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/Application.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/CharacterVision.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/Geometrics.java
  src/test/java/headless/GeometricsTest.java
  src/test/java/headless/VisionTest.java
Labels: enhancement

#28 27 decouple repositories
  build.gradle
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/Factory.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IMapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IPlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Area.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Intruder.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Item.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Player.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Tile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/TileArea.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/GameRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/MapRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/PlayerRepository.java
  src/main/java/module-info.java
  src/test/java/headless/FactoryTest.java
  src/test/java/headless/MapImporterTest.java
Labels: enhancement

#32 Basic agent Structure
  build.gradle
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/Application.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/IAgent.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/frontier/yamauchi/Frontier.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/frontier/yamauchi/QueueNode.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/frontier/yamauchi/YamauchiAgent.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/frontier/yamauchi/exceptions/NoFrontiersException.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/random/RandomAgent.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/agents/shared/Agent.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/GameBoardGUI.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/GameController.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/TestGUI.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/terminal/Simulator.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/terminal/TerminalApp.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/contracts/repositories/IPlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Area.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Collision.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/ItemType.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Player.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/Tile.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/models/TileArea.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/PlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/CharacterVision.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/Geometrics.java
  src/main/java/module-info.java
  src/main/resources/META-INF/MANIFEST.MF
  src/test/java/headless/ExplorationTest.java
  src/test/java/headless/GeometricsTest.java
  src/test/java/headless/MapBuildTest.java
  src/test/java/headless/MapImporterTest.java
  src/test/java/headless/TileAreaTest.java
  src/test/java/headless/VisionTest.java
  src/test/java/headless/YamauchiAgentTest.java
  src/test/resources/maps/testmap2.txt
Labels: enhancement

#33 Vision fix
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/GameController.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/terminal/Simulator.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/repositories/PlayerRepository.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/CharacterVision.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/headless/utils/Geometrics.java
  src/test/java/headless/VisionTest.java
  src/test/resources/maps/testmap3.txt
Labels: bug

#38 Homescreen
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/assets/style.css
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/GameController.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/HomeScreen.java
  src/main/java/com/nscharrenberg/um/multiagentsurveillance/gui/javafx/controllers/TestGUI.java
Labels: enhancement
